# Generated by Django 4.0.4 on 2022-06-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profissional_imagem_profissional_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='image',
            new_name='imagem',
        ),
    ]
