# Generated by Django 4.0.4 on 2022-06-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profissional_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='imagem',
        ),
    ]
