# Generated by Django 4.0.4 on 2022-06-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profissional_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='atividades',
            field=models.CharField(max_length=200, verbose_name='Profissão'),
        ),
    ]
